---
- name: Set up new Raspberry
  hosts: raspberry
  roles:
    - role: connect
    - role: update
    # - role: copy_public_key
    # - role: install_remote_desktop
    # - role: install_docker
    # - role: install_java
    #- role: set_ip
