---
- name: Download docker
  shell: curl -sSL https://get.docker.com | sh

- name: Fix permision
  shell: usermod -aG docker $USER
  become: yes
  become_user: root

- name: Restart docker
  shell: service docker restart
  become: yes
  become_user: root

- name: install docker-compose
  shell: pip3 install docker-compose
  become: yes
  become_user: root
