---
- name: Update apt
  shell: apt -y update
  become: yes
  become_user: root

- name: Upgrade apt
  shell: apt -y upgrade
  become: yes
  become_user: root

- name: Update apt-get
  shell: apt-get -y update
  args:
    warn: false
  become: yes
  become_user: root

- name: Upgrade apt-get
  shell: apt-get -y upgrade
  args:
    warn: false
  become: yes
  become_user: root
