---
- name: Update apt
  shell: apt update
  become: yes
  become_user: root

- name: Upgrade apt
  shell: apt upgrade
  become: yes
  become_user: root

- name: Update apt-get
  shell: apt-get update
  become: yes
  become_user: root

- name: Upgrade apt-get
  shell: apt-get upgrade
  become: yes
  become_user: root
