---
- name: Install dependencies
  shell: apt-get install -y haproxy
  become: yes
  become_user: root

# - name: Create https certification
#   shell: certbot -d app.cortijodemazas.com --manual --preferred-challenges dns certonly
#   become: yes
#   become_user: root
